<template>
    
    <div class="cardBackground">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
    </div>
</template>

<script>
export default {
    
}
</script>

<style scoped>

    .cardBackground{
        border-radius: 10pt;
        background-color: #F8F8F8;
        box-shadow: 0 0 10pt #00000029;
        padding: 8px;
        margin: 5px;
    }

</style>